http_port 3128
pid_filename /tmp/squid.pid

acl SSL_ports port 443
acl CONNECT method CONNECT
acl allowed_domains dstdomain .github.com .githubusercontent.com registry.npmjs.org

http_access deny CONNECT !SSL_ports
http_access allow allowed_domains
http_access deny all

cache deny all
access_log none
cache_log /tmp/squid-cache.log
cache_store_log none
coredump_dir /tmp
